[features]
seeds = false
skip-lint = false
[programs.devnet]
new_mint = "2VtTTJyAVt8GCi6eDPNGpAa42XaWrB6bDtfA8srcRxJ6"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/viandwi24/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
