[features]
seeds = false
skip-lint = false
[programs.devnet]
sc_calculator = "7ATMSJ1J7qop76bFuK7bfeeKmx94ogPprx4WZC4KMKhM"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/viandwi24/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
