[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "7b8Heiw5c2dTcfQQwGELahjaGhGyRVHiMiXpSX3o5vMB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/viandwi24/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
